---
version: 1.2.0
slug: assist_personal_microphone
name: Assist Personal Microphone
description: Use Assist with local microphone
url: https://github.com/youssseeef-assistant/assist-personal-microphone/blob/master
hassio_api: true
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:ro
options:
  awake_wav: "/usr/src/sounds/awake.wav"
  done_wav: "/usr/src/sounds/done.wav"
  timer_finished_wav: "/usr/src/sounds/timer-finished.wav"
  sound_enabled: true
  noise_suppression: 0
  auto_gain: 0
  mic_volume_multiplier: 1.0
  sound_volume_multiplier: 1.0
  debug_logging: false
schema:
  awake_wav: str
  done_wav: str
  timer_finished_wav: str
  sound_enabled: bool
  noise_suppression: int
  auto_gain: int
  mic_volume_multiplier: float
  sound_volume_multiplier: float
  debug_logging: bool
audio: true
homeassistant: 2023.12.1
image: homeassistant/{arch}-addon-assist_microphone
